In [1]:
import tensorflow as tf
from keras.applications.efficientnet import EfficientNetB4
from SegmentationModels import DeepLabV3plus, Unet
from DatasetUtils import Dataset
from keras.applications import resnet, resnet_v2, densenet, efficientnet, efficientnet_v2

2022-11-21 18:07:42.314166: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [9]:
img = tf.random.uniform((5, 5, 3), minval=0, maxval=255, dtype=tf.dtypes.int32)
img = tf.cast(img, tf.dtypes.float32)
img.numpy()

array([[[136., 250., 248.],
        [ 67.,  20., 133.],
        [ 68., 224., 173.],
        [244.,  39., 180.],
        [ 56., 220., 103.]],

       [[136., 153., 157.],
        [198., 196., 179.],
        [ 41.,  66.,   8.],
        [227., 175., 110.],
        [ 82., 187.,  58.]],

       [[102., 139.,  60.],
        [200., 117.,  94.],
        [ 71.,  29.,  83.],
        [138., 150., 180.],
        [152., 114., 132.]],

       [[ 31.,  89.,  21.],
        [153., 249., 235.],
        [107., 114., 251.],
        [203., 198., 216.],
        [161., 157., 247.]],

       [[ 14.,  35., 232.],
        [ 63., 221.,  76.],
        [123., 224., 248.],
        [ 93., 182.,  46.],
        [ 28.,  42., 147.]]], dtype=float32)

In [10]:
p_img = resnet.preprocess_input(img)
p_img.numpy()

array([[[ 144.061     ,  133.22101   ,   12.32      ],
        [  29.060997  ,  -96.779     ,  -56.68      ],
        [  69.061     ,  107.221     ,  -55.68      ],
        [  76.061     ,  -77.779     ,  120.32      ],
        [  -0.939003  ,  103.221     ,  -67.68      ]],

       [[  53.060997  ,   36.221     ,   12.32      ],
        [  75.061     ,   79.221     ,   74.32      ],
        [ -95.939     ,  -50.779     ,  -82.68      ],
        [   6.060997  ,   58.221     ,  103.32      ],
        [ -45.939003  ,   70.221     ,  -41.68      ]],

       [[ -43.939003  ,   22.221     ,  -21.68      ],
        [  -9.939003  ,    0.22100067,   76.32      ],
        [ -20.939003  ,  -87.779     ,  -52.68      ],
        [  76.061     ,   33.221     ,   14.32      ],
        [  28.060997  ,   -2.7789993 ,   28.32      ]],

       [[ -82.939     ,  -27.779     ,  -92.68      ],
        [ 131.061     ,  132.22101   ,   29.32      ],
        [ 147.061     ,   -2.7789993 ,  -16.68      ],
    

In [11]:
p_img = resnet_v2.preprocess_input(img)
p_img.numpy()

array([[[ 0.06666672,  0.9607843 ,  0.94509804],
        [-0.47450978, -0.84313726,  0.04313731],
        [-0.46666664,  0.75686276,  0.35686278],
        [ 0.9137255 , -0.69411767,  0.41176474],
        [-0.56078434,  0.7254902 , -0.19215685]],

       [[ 0.06666672,  0.20000005,  0.2313726 ],
        [ 0.5529412 ,  0.5372549 ,  0.4039216 ],
        [-0.6784314 , -0.4823529 , -0.9372549 ],
        [ 0.78039217,  0.37254906, -0.1372549 ],
        [-0.35686272,  0.4666667 , -0.54509807]],

       [[-0.19999999,  0.09019613, -0.5294118 ],
        [ 0.5686275 , -0.08235294, -0.26274508],
        [-0.44313723, -0.77254903, -0.3490196 ],
        [ 0.082353  ,  0.17647064,  0.41176474],
        [ 0.19215691, -0.10588235,  0.03529418]],

       [[-0.75686276, -0.30196077, -0.8352941 ],
        [ 0.20000005,  0.9529412 ,  0.84313726],
        [-0.1607843 , -0.10588235,  0.96862745],
        [ 0.5921569 ,  0.5529412 ,  0.69411767],
        [ 0.26274514,  0.2313726 ,  0.9372549 ]],

       [[-0.

In [12]:
p_img = efficientnet.preprocess_input(img)
p_img.numpy()

array([[[136., 250., 248.],
        [ 67.,  20., 133.],
        [ 68., 224., 173.],
        [244.,  39., 180.],
        [ 56., 220., 103.]],

       [[136., 153., 157.],
        [198., 196., 179.],
        [ 41.,  66.,   8.],
        [227., 175., 110.],
        [ 82., 187.,  58.]],

       [[102., 139.,  60.],
        [200., 117.,  94.],
        [ 71.,  29.,  83.],
        [138., 150., 180.],
        [152., 114., 132.]],

       [[ 31.,  89.,  21.],
        [153., 249., 235.],
        [107., 114., 251.],
        [203., 198., 216.],
        [161., 157., 247.]],

       [[ 14.,  35., 232.],
        [ 63., 221.,  76.],
        [123., 224., 248.],
        [ 93., 182.,  46.],
        [ 28.,  42., 147.]]], dtype=float32)

In [13]:
p_img = efficientnet_v2.preprocess_input(img)
p_img.numpy()

array([[[136., 250., 248.],
        [ 67.,  20., 133.],
        [ 68., 224., 173.],
        [244.,  39., 180.],
        [ 56., 220., 103.]],

       [[136., 153., 157.],
        [198., 196., 179.],
        [ 41.,  66.,   8.],
        [227., 175., 110.],
        [ 82., 187.,  58.]],

       [[102., 139.,  60.],
        [200., 117.,  94.],
        [ 71.,  29.,  83.],
        [138., 150., 180.],
        [152., 114., 132.]],

       [[ 31.,  89.,  21.],
        [153., 249., 235.],
        [107., 114., 251.],
        [203., 198., 216.],
        [161., 157., 247.]],

       [[ 14.,  35., 232.],
        [ 63., 221.,  76.],
        [123., 224., 248.],
        [ 93., 182.,  46.],
        [ 28.,  42., 147.]]], dtype=float32)

In [14]:
p_img = densenet.preprocess_input(img)
p_img.numpy()

array([[[ 0.21106265,  2.3410363 ,  2.5179958 ],
        [-0.9705454 , -1.6855742 ,  0.51363856],
        [-0.95342064,  1.8858544 ,  1.2108063 ],
        [ 2.060536  , -1.352941  ,  1.3328106 ],
        [-1.1589178 ,  1.8158263 , -0.0092374 ]],

       [[ 0.21106265,  0.64285725,  0.9319392 ],
        [ 1.2727973 ,  1.3956583 ,  1.3153814 ],
        [-1.4157891 , -0.880252  , -1.6650109 ],
        [ 1.7694151 ,  1.0280112 ,  0.11276696],
        [-0.7136741 ,  1.2380953 , -0.79355115]],

       [[-0.37117907,  0.3977592 , -0.7586928 ],
        [ 1.3070468 ,  0.01260505, -0.16610013],
        [-0.9020464 , -1.5280112 , -0.35782126],
        [ 0.24531215,  0.5903362 ,  1.3328106 ],
        [ 0.4850587 , -0.03991595,  0.49620935]],

       [[-1.5870366 , -0.47759098, -1.4384314 ],
        [ 0.50218344,  2.3235295 ,  2.2914162 ],
        [-0.2855553 , -0.03991595,  2.5702832 ],
        [ 1.3584211 ,  1.4306723 ,  1.9602616 ],
        [ 0.63918144,  0.71288526,  2.5005665 ]],

       [[-1.

In [ ]:
model = DeepLabV3plus(input_shape=(1024,2048,3),
                        filters=[16,32,64,128,256],
                        num_classes=20,
                        activation='leaky_relu',
                        dropout_rate=0.0,
                        backbone_name='EfficientNetB4',
                        freeze_backbone=False,
                        unfreeze_at='block6a_expand_activation'
                        )

model.summary()

In [ ]:
tf.keras.utils.plot_model(model,
                          f"{model.name}.png",
                          show_shapes=True)