In [1]:
import tensorflow as tf
from keras.applications.efficientnet import EfficientNetB4
from SegmentationModels import DeepLabV3plus, Unet
from DatasetUtils import Dataset
from keras.applications import resnet, resnet_v2, densenet, efficientnet, efficientnet_v2

2022-11-21 12:40:48.761242: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [8]:
img = tf.random.uniform((5, 5, 3), minval=0, maxval=255, dtype=tf.dtypes.int32)
img = tf.cast(img, tf.dtypes.float32)
img.numpy()

array([[[ 87., 161., 175.],
        [134., 226., 126.],
        [ 59.,  64., 149.],
        [182., 145., 197.],
        [ 83., 180.,   5.]],

       [[ 70.,  38.,  60.],
        [207., 232., 162.],
        [ 30., 251., 184.],
        [109., 197.,  68.],
        [201., 147., 221.]],

       [[ 18., 151., 116.],
        [159.,  14.,  87.],
        [104., 167.,  76.],
        [188.,  96., 236.],
        [118., 226.,  21.]],

       [[186.,  82., 214.],
        [246., 181., 247.],
        [163., 145.,  98.],
        [ 17.,  27.,  58.],
        [ 21., 189.,  90.]],

       [[ 37., 240., 223.],
        [190., 191.,  47.],
        [ 53., 117.,  57.],
        [  6., 151., 179.],
        [ 25.,   4., 146.]]], dtype=float32)

In [9]:
p_img = resnet.preprocess_input(img)
p_img.numpy()

array([[[  71.061     ,   44.221     ,  -36.68      ],
        [  22.060997  ,  109.221     ,   10.32      ],
        [  45.060997  ,  -52.779     ,  -64.68      ],
        [  93.061     ,   28.221     ,   58.32      ],
        [ -98.939     ,   63.221     ,  -40.68      ]],

       [[ -43.939003  ,  -78.779     ,  -53.68      ],
        [  58.060997  ,  115.221     ,   83.32      ],
        [  80.061     ,  134.22101   ,  -93.68      ],
        [ -35.939003  ,   80.221     ,  -14.68      ],
        [ 117.061     ,   30.221     ,   77.32      ]],

       [[  12.060997  ,   34.221     , -105.68      ],
        [ -16.939003  , -102.779     ,   35.32      ],
        [ -27.939003  ,   50.221     ,  -19.68      ],
        [ 132.061     ,  -20.779     ,   64.32      ],
        [ -82.939     ,  109.221     ,   -5.6800003 ]],

       [[ 110.061     ,  -34.779     ,   62.32      ],
        [ 143.061     ,   64.221     ,  122.32      ],
        [  -5.939003  ,   28.221     ,   39.32      ],
    

In [11]:
p_img = resnet_v2.preprocess_input(img)
p_img.numpy()

array([[[-0.31764704,  0.26274514,  0.37254906],
        [ 0.05098045,  0.77254903, -0.01176471],
        [-0.5372549 , -0.4980392 ,  0.1686275 ],
        [ 0.427451  ,  0.13725495,  0.54509807],
        [-0.3490196 ,  0.41176474, -0.9607843 ]],

       [[-0.45098037, -0.7019608 , -0.5294118 ],
        [ 0.62352943,  0.81960785,  0.27058828],
        [-0.7647059 ,  0.96862745,  0.4431373 ],
        [-0.14509803,  0.54509807, -0.46666664],
        [ 0.5764706 ,  0.15294123,  0.73333335]],

       [[-0.85882354,  0.18431377, -0.09019607],
        [ 0.24705887, -0.8901961 , -0.31764704],
        [-0.18431371,  0.30980396, -0.40392154],
        [ 0.47450984, -0.24705881,  0.8509804 ],
        [-0.0745098 ,  0.77254903, -0.8352941 ]],

       [[ 0.45882356, -0.35686272,  0.6784314 ],
        [ 0.92941177,  0.41960788,  0.9372549 ],
        [ 0.27843142,  0.13725495, -0.23137254],
        [-0.8666667 , -0.7882353 , -0.54509807],
        [-0.8352941 ,  0.48235297, -0.29411763]],

       [[-0.

In [10]:
p_img = efficientnet.preprocess_input(img)
p_img.numpy()

array([[[ 87., 161., 175.],
        [134., 226., 126.],
        [ 59.,  64., 149.],
        [182., 145., 197.],
        [ 83., 180.,   5.]],

       [[ 70.,  38.,  60.],
        [207., 232., 162.],
        [ 30., 251., 184.],
        [109., 197.,  68.],
        [201., 147., 221.]],

       [[ 18., 151., 116.],
        [159.,  14.,  87.],
        [104., 167.,  76.],
        [188.,  96., 236.],
        [118., 226.,  21.]],

       [[186.,  82., 214.],
        [246., 181., 247.],
        [163., 145.,  98.],
        [ 17.,  27.,  58.],
        [ 21., 189.,  90.]],

       [[ 37., 240., 223.],
        [190., 191.,  47.],
        [ 53., 117.,  57.],
        [  6., 151., 179.],
        [ 25.,   4., 146.]]], dtype=float32)

In [14]:
p_img = efficientnet_v2.preprocess_input(img)
p_img.numpy()

array([[[ 87., 161., 175.],
        [134., 226., 126.],
        [ 59.,  64., 149.],
        [182., 145., 197.],
        [ 83., 180.,   5.]],

       [[ 70.,  38.,  60.],
        [207., 232., 162.],
        [ 30., 251., 184.],
        [109., 197.,  68.],
        [201., 147., 221.]],

       [[ 18., 151., 116.],
        [159.,  14.,  87.],
        [104., 167.,  76.],
        [188.,  96., 236.],
        [118., 226.,  21.]],

       [[186.,  82., 214.],
        [246., 181., 247.],
        [163., 145.,  98.],
        [ 17.,  27.,  58.],
        [ 21., 189.,  90.]],

       [[ 37., 240., 223.],
        [190., 191.,  47.],
        [ 53., 117.,  57.],
        [  6., 151., 179.],
        [ 25.,   4., 146.]]], dtype=float32)

In [15]:
p_img = densenet.preprocess_input(img)
p_img.numpy()

array([[[-0.6280504 ,  0.78291327,  1.2456646 ],
        [ 0.17681314,  1.9208683 ,  0.39163405],
        [-1.1075436 , -0.91526604,  0.7925056 ],
        [ 0.9988013 ,  0.50280124,  1.6291069 ],
        [-0.69654936,  1.1155462 , -1.7172985 ]],

       [[-0.91917115, -1.370448  , -0.7586928 ],
        [ 1.42692   ,  2.0259104 ,  1.0190852 ],
        [-1.6041614 ,  2.3585434 ,  1.4025275 ],
        [-0.25130582,  1.4131653 , -0.6192592 ],
        [ 1.3241715 ,  0.5378152 ,  2.0474076 ]],

       [[-1.8096584 ,  0.6078432 ,  0.21734212],
        [ 0.60493195, -1.7906162 , -0.28810447],
        [-0.33692956,  0.88795525, -0.47982562],
        [ 1.1015497 , -0.35504198,  2.3088455 ],
        [-0.09718303,  1.9208683 , -1.4384314 ]],

       [[ 1.0673003 , -0.60014   ,  1.9254032 ],
        [ 2.0947855 ,  1.1330533 ,  2.5005665 ],
        [ 0.673431  ,  0.50280124, -0.09638336],
        [-1.8267832 , -1.5630252 , -0.79355115],
        [-1.7582842 ,  1.2731093 , -0.23581691]],

       [[-1.

In [ ]:
model = DeepLabV3plus(input_shape=(1024,2048,3),
                        filters=[16,32,64,128,256],
                        num_classes=20,
                        activation='leaky_relu',
                        dropout_rate=0.0,
                        backbone_name='EfficientNetB4',
                        freeze_backbone=False,
                        unfreeze_at='block6a_expand_activation'
                        )

model.summary()

In [ ]:
tf.keras.utils.plot_model(model,
                          f"{model.name}.png",
                          show_shapes=True)